---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and LInt
    runs-on: ubuntu-20.04 #runner will be using to run our job
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
          uses: actions/checkout@v2
      - name: Test
          run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm sh -c "flake8"